version: '2'
services:

  giteadb:
    image: mariadb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=netserver
      - MYSQL_DATABASE=gitea
      - MYSQL_USER=gitea
      - MYSQL_PASSWORD=netserver
    # ports:
    #   - 3306:3306/tcp
    command:
      --character-set-server=utf8
      --collation-server=utf8_general_ci
      --default-storage-engine=innodb
      --innodb_file_per_table=on
      --max_connections=4096
    volumes:
      - gitea_db_data:/var/lib/mysql
    networks:
      gitea:

  gitea:
    image: gitea/gitea
    restart: always
    ports:
      - 3000:3000/tcp
      - 3022:22/tcp
    networks:
      gitea:

networks:
  gitea:

volumes:
  gitea_db_data:
